// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ZnLfaWOLL5Je44iHWoREk3DNee-oU6o',
    appId: '1:943688238219:android:3bf03ae83406e54b43c08e',
    messagingSenderId: '943688238219',
    projectId: 'havruta-app',
    storageBucket: 'havruta-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5B9BlRR_OsNpsAa9klwlRbMAGyPIHt-4',
    appId: '1:943688238219:ios:eb5bde2a3894ebdb43c08e',
    messagingSenderId: '943688238219',
    projectId: 'havruta-app',
    storageBucket: 'havruta-app.firebasestorage.app',
    iosBundleId: 'com.example.havruta',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkt9z8JES3Pvcs18xBAES5_Dy0Z3xGWxg',
    appId: '1:943688238219:web:64ffe33b31f0850043c08e',
    messagingSenderId: '943688238219',
    projectId: 'havruta-app',
    authDomain: 'havruta-app.firebaseapp.com',
    storageBucket: 'havruta-app.firebasestorage.app',
  );

}